apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oz-postgres
  labels:
    app: oz-postgres
spec:
  serviceName: oz-postgres
  replicas: 1
  selector:
    matchLabels:
      app: oz-postgres
  template:
    metadata:
      labels:
        app: oz-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: oz-postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: oz-postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: oz-postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
