apiVersion: v1
kind: Service
metadata:
  name: oz-postgres
  labels:
    app: oz-postgres
spec:
  selector:
    app: oz-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
