apiVersion: v1
kind: Service
metadata:
  name: oz-workspace
  labels:
    app: oz-workspace
spec:
  selector:
    app: oz-workspace
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
